name: ASP.NET CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: Publish
      run: msbuild /p:Configuration=Release /t:Publish

    - name: Deploy to IIS
      run: |
        $webAppPath = 'C:\inetpub\wwwroot\WebApplication1'  # Update with your application path in the IIS server
        Remove-Item -Path $webAppPath -Recurse -Force -ErrorAction SilentlyContinue
        Copy-Item -Path 'WebApplication1/Properties/PublishProfiles*' -Destination $webAppPath -Recurse
